/**
 * THE CONTRACT
 * ============
 *
 * Every subsystem codes against this file and nothing else. It exists so that
 * eight agents can work in parallel without reading each other's code.
 *
 * DO NOT EDIT THIS FILE AS A SIDE EFFECT OF ANOTHER CHANGE. Widening the
 * contract invalidates every other agent's assumptions at the same moment. If a
 * change genuinely needs new surface, that is its own commit, announced, and it
 * re-runs every harness.
 *
 * Sibling imports are banned. `src/render/` may not import from `src/world/`.
 * Everything crosses through `GameServices`, `EventBus`, or this file.
 *
 * Read these four sections before writing anything:
 *   STEERING SIGN      - the sign convention, stated once, negated nowhere else
 *   THE CLOCK          - fixed-step simulation; wall clock never reaches physics
 *   DETERMINISM        - per-namespace RNG; why the same seed must rebuild the same city
 *   ALLOCATION         - which paths are actually zero-allocation, and which are not
 */

import type {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  Object3D,
  PerspectiveCamera,
  Quaternion,
  Scene,
  Vector3,
  WebGLRenderer,
} from 'three'

// ---------------------------------------------------------------------------
// Units
// ---------------------------------------------------------------------------
// Distance: metres. Time: seconds. Angle: radians. Speed: m/s. Mass: kg.
// The HUD is the only place allowed to convert to km/h, and it does it once, at
// the point of display. A speed stored in km/h anywhere else will drift out of
// sync with the physics and nothing will report an error.

export type Seconds = number
export type Metres = number
export type Radians = number

/** World axes: +X right, +Y up, -Z forward at identity rotation. */
export const WORLD_FORWARD = { x: 0, y: 0, z: -1 } as const
export const WORLD_UP = { x: 0, y: 1, z: 0 } as const

// ---------------------------------------------------------------------------
// THE CLOCK
// ---------------------------------------------------------------------------
/**
 * The simulation advances in fixed integer ticks. Wall-clock deltas never reach
 * physics, AI, race progression or item logic.
 *
 * This is a measurement requirement before it is a physics one. A variable
 * timestep makes substep counts machine-dependent, which makes collision
 * outcomes, AI lines, lap times and therefore every screenshot and every drift
 * benchmark depend on how busy the laptop was. Two rounds would not be
 * comparable, and the loop grades by comparison.
 *
 * The frame loop accumulates real time, runs whole steps up to MAX_CATCHUP_STEPS
 * (beyond which it drops the debt rather than spiralling), and hands `alpha` to
 * the visual layer for interpolation.
 */
export const SIMULATION_STEP: Seconds = 1 / 120
export const MAX_CATCHUP_STEPS = 8

export interface Clock {
  /** Integer simulation ticks since boot. The authoritative time coordinate. */
  readonly tick: number
  /** `tick * SIMULATION_STEP`. Never read `performance.now()` in a subsystem. */
  readonly simTime: Seconds
  /** [0, 1) interpolation factor between the last two ticks. Visual layer only. */
  readonly alpha: number
  /** True while the simulation is halted. Distinct from `RacePhase`. */
  readonly paused: boolean
}

// ---------------------------------------------------------------------------
// STEERING SIGN
// ---------------------------------------------------------------------------
/**
 * `steer > 0` ALWAYS means "steer toward the driver's right", for every caller,
 * human or AI, at every layer.
 *
 * There is exactly one conversion from this intent to yaw torque and it lives
 * inside `IKart.step`. No caller negates. No caller compensates. The AI solves
 * for a lateral target and expresses the result in this same intent space; if
 * an AI implementation finds itself flipping a sign to make karts turn the
 * right way, the bug is in the AI's frame maths, not in this convention.
 *
 * `tools/steer-test.mjs` asserts it end to end for both a scripted player input
 * and the reference AI. Run it after touching either.
 */
export interface InputFrame {
  /** -1 (hard left) .. +1 (hard right). Positive = driver's right. */
  steer: number
  /** 0 .. 1 */
  throttle: number
  /** 0 .. 1 */
  brake: number
  /** Level, not edge. Drift begins on a rising edge while turning, ends on fall. */
  drift: boolean
  /**
   * ONE-TICK PULSE, not a held level. Whoever produces an InputFrame sets this
   * true for exactly one simulation tick. `game/` consumes it and calls
   * `IItems.use`; nothing else edge-detects it.
   */
  useItem: boolean
  /** -1 look fully back .. +1 look ahead. 0 = default chase camera. */
  look: number
}

export type InputKind = 'keyboard' | 'touch' | 'gamepad'

export interface IInput {
  readonly kind: InputKind
  /** Stable object. Read fields; never retain the object across a tick. */
  readonly frame: Readonly<InputFrame>
  /**
   * Wall-clock milliseconds (`performance.now()` domain) at which the most
   * recent hardware event contributing to `frame` was received. The latency
   * harness compares this against the tick that consumed it; without it,
   * measuring kart displacement measures physics response, not input latency.
   */
  readonly lastEventAtMs: number
  sample(clock: Clock): void
  dispose(): void
}

// ---------------------------------------------------------------------------
// Surfaces
// ---------------------------------------------------------------------------
/**
 * A desert circuit is defined by what the road does to grip and to sightlines.
 * Surface drives physics, particle choice, tyre audio and reflection strength,
 * so it is one shared enum rather than four private ones that drift apart.
 *
 * Plain enum, not `const enum`: the build runs with `isolatedModules`, under
 * which `const enum` is a compile error, and inlined values would let a stale
 * consumer silently disagree with a rebuilt one.
 *
 * ORDINALS ARE HELD ACROSS THE THEME CHANGE. Eight members before, eight after,
 * same numbers. `Readonly<Record<Surface, SurfaceProps>>` then keeps working as
 * a compiler-enforced checklist — miss a key and `tsc --noEmit` fails, which is
 * the safety net you want on a table this size.
 */
export enum Surface {
  /** Clean sealed tarmac, under overhangs and in the slot canyon. Reference grip. */
  Asphalt = 0,
  /** The default road: a sand film over tarmac. Slightly lower grip, matte. */
  DustyAsphalt = 1,
  /** Windblown sand across the road. Lowest grip, high drag, throws a rooster tail. */
  SandDrift = 2,
  /** Painted kerb. Grippy, but rumbles chassis and camera. */
  Kerb = 3,
  /** Cattle grid and culvert grates. Grip collapses when crossed at an angle. */
  Metal = 4,
  /** Scree and washout off the canyon wall. Loose and slow. */
  Gravel = 5,
  /** Boost strip. Clean grip plus a forced boost on contact. */
  BoostPad = 6,
  /** Past the barrier line. Heavy drag; `game/` respawns after a grace period. */
  OffTrack = 7,
}

export interface SurfaceProps {
  /** Multiplier on peak tyre force. `Asphalt` is 1.0 by definition. */
  readonly grip: number
  /**
   * Longitudinal drag deceleration, in m/s², evaluated at 30 m/s. It scales
   * quadratically with speed:
   *
   *     a_drag = dragAccelAt30 * (speed / 30)^2,  opposing velocity
   *
   * Stated as a formula because "drag" alone permits constant, linear and
   * quadratic readings, and three subsystems tuning against three different
   * curves produces a kart that nobody can balance.
   */
  readonly dragAccelAt30: number
  /** Chassis perturbation amplitude in metres. Drives rumble and camera shake. */
  readonly roughness: number
  /** Particle family; `fx/` owns what each one looks like. */
  readonly spray: 'none' | 'dust' | 'sand' | 'sparks'
  /**
   * Mixed into reflection strength. 0 = matte, 1 = mirror.
   *
   * Was `wetness`. The semantics were always generic — only the name was
   * theme-specific — and leaving it called `wetness` on a dry circuit leaves a
   * dead axis that `fx/` would multiply spray rate by and get zero from.
   */
  readonly reflectivity: number
}

/**
 * TUNING, not structure. Adjusting a number in this table is a balance change
 * and is NOT a contract change — it does not need the announcement ritual.
 * Adding or removing a `Surface` member is.
 *
 * NOTHING IN THE GRIP OR DRAG COLUMNS MOVED ACROSS THE THEME CHANGE, on purpose.
 * The obvious instinct is that a dry road should be grippier than a wet one, so
 * `DustyAsphalt` wants to go from 0.88 to 0.92. Resist it. This is the default
 * road, it covers most of the lap, and a 4.5% grip rise moves every lap time,
 * every AI corner-entry speed and the drift-initiation threshold — which is to
 * say it moves §10c criteria 1 and 2, the two gates the whole game is judged on.
 * A sand film over tarmac justifies 0.88 perfectly well. Raise it later, alone,
 * measured.
 *
 * The only non-cosmetic changes are the two chassis-perturbation bumps
 * (`roughness` here means bump amplitude in metres, not material roughness):
 * sand should feel like sand, and 0.02 does not.
 */
export const SURFACE_PROPS: Readonly<Record<Surface, SurfaceProps>> = {
  [Surface.Asphalt]: { grip: 1.0, dragAccelAt30: 0.0, roughness: 0.01, spray: 'none', reflectivity: 0.1 },
  [Surface.DustyAsphalt]: { grip: 0.88, dragAccelAt30: 0.0, roughness: 0.02, spray: 'dust', reflectivity: 0.06 },
  [Surface.SandDrift]: { grip: 0.62, dragAccelAt30: 1.6, roughness: 0.07, spray: 'sand', reflectivity: 0.03 },
  [Surface.Kerb]: { grip: 0.95, dragAccelAt30: 0.4, roughness: 0.06, spray: 'sparks', reflectivity: 0.3 },
  [Surface.Metal]: { grip: 0.55, dragAccelAt30: 0.0, roughness: 0.02, spray: 'sparks', reflectivity: 0.35 },
  [Surface.Gravel]: { grip: 0.7, dragAccelAt30: 4.5, roughness: 0.09, spray: 'dust', reflectivity: 0.05 },
  [Surface.BoostPad]: { grip: 1.0, dragAccelAt30: 0.0, roughness: 0.01, spray: 'sparks', reflectivity: 0.55 },
  [Surface.OffTrack]: { grip: 0.5, dragAccelAt30: 9.0, roughness: 0.12, spray: 'dust', reflectivity: 0.05 },
}

// ---------------------------------------------------------------------------
// Track
// ---------------------------------------------------------------------------

/**
 * Mutable by design: `ITrack.sample` and `ITrack.locate` write into a
 * caller-owned instance. That is what makes them allocation-free without
 * handing out a shared pooled object that a careless caller can retain past the
 * point where it stays valid.
 */
export interface TrackSample {
  /** Centreline point, world space. */
  position: Vector3
  /** Unit vector, direction of travel. */
  tangent: Vector3
  /** Road up, already rotated by the bank angle. */
  normal: Vector3
  /** `tangent × normal`; points to the driver's right. */
  right: Vector3
  halfWidth: Metres
  /** Positive banks the road down toward the driver's right. */
  bank: Radians
  /** Signed 1/m. Positive curves right. AI picks entry speed from this. */
  curvature: number
}

export interface TrackLocation {
  /** Normalised distance along the centreline, [0, 1). */
  t: number
  /** Signed metres from the centreline; positive is the driver's right. */
  lateral: Metres
  /** Metres above the road plane at that point. */
  height: Metres
  /** False once `|lateral| > halfWidth + BARRIER_MARGIN`. */
  onTrack: boolean
  /** Index of the last checkpoint at or before `t`. */
  checkpointIndex: number
}

/** Metres of shoulder beyond `halfWidth` before a kart counts as off track. */
export const BARRIER_MARGIN: Metres = 1.5

export interface StartSlot {
  readonly position: Vector3
  /**
   * Full orientation, not a yaw scalar. The grid, the ramp and the banked bend
   * are not level, and a yaw-only heading spawns karts intersecting the road or
   * facing uphill with no way to express the difference.
   */
  readonly orientation: Quaternion
  /** Track coordinate of this slot, for respawn and telemetry. */
  readonly t: number
}

export interface ITrack {
  /** Centreline length in metres. */
  readonly length: Metres
  /** Scene node owned by `world/`. No other subsystem adds children to it. */
  readonly group: Object3D
  /**
   * `t` wraps; callers never clamp. Writes into `out` and returns it.
   * Allocation-free. `out` belongs to the caller — keep one per call site.
   */
  sample(t: number, out: TrackSample): TrackSample
  /** Project a world point onto the centreline. Writes into `out`, returns it. */
  locate(p: Vector3, out: TrackLocation): TrackLocation
  /** Outside every defined surface region this returns `Surface.OffTrack`. */
  surfaceAt(t: number, lateral: Metres): Surface
  /** Lateral offset in metres of the ideal line at `t`. AI and ghost use it. */
  racingLine(t: number): Metres
  /**
   * Signed lateral offset of the COLLIDABLE canyon face on one side at `t`.
   * `side` follows STEERING SIGN: +1 is the driver's right, and the returned
   * value carries that sign, so `wallLimit(t, +1) > 0`.
   *
   * WHY THIS IS ON THE CONTRACT AND NOT DERIVED BY THE CALLER. A kart cannot
   * compute it: the envelope is `halfWidth + setback - talusRun`, where
   * `setback` comes from an eight-row table private to `world/terrain.ts` and
   * `talusRun` from that section's height over `tan(32°)`, all noise-modulated
   * from `ctx.rngFor` streams. Measured over 480 rays, the face sits between
   * 0.55 m and 53.87 m beyond the road edge — a factor of 5.2 in the ratio to
   * `halfWidth`. THERE IS NO CONSTANT AND NO MULTIPLE THAT WORKS: pick the low
   * end and you put walls on the shoulder, deleting `Surface.OffTrack`; pick
   * the high end and you are 27 m inside The Slot's rock. `src/kart/` may not
   * import `src/world/`, so this is the channel.
   *
   * NEVER inboard of `halfWidth + BARRIER_MARGIN`. Off-track driving is a
   * designed penalty — grip 0.5, drag 9.0 — and a barrier must not delete it.
   * `world/` already clamps its toe to exactly that line.
   *
   * Measured at chassis height, not at the crest: `world/` guarantees nothing
   * overhangs below 4 m, so one lateral number is sufficient for a kart.
   *
   * Returns `Infinity` where the section has no wall. That is a legal answer
   * and means "no barrier", not "unknown" — a caller must treat a non-finite
   * value as free space rather than clamping to it.
   *
   * Allocation-free, and on the MUST NOT ALLOCATE list beside `surfaceAt`.
   */
  wallLimit(t: number, side: -1 | 1): Metres
  /**
   * Ordered, ascending, `checkpoints[0] === 0` (the start line). A lap counts
   * only when every checkpoint was crossed in ascending index order, each in
   * the forward direction; crossing backward decrements. Wrapping from the last
   * index to 0 is what completes the lap.
   */
  readonly checkpoints: readonly number[]
  readonly startGrid: readonly StartSlot[]
}

// ---------------------------------------------------------------------------
// Kart
// ---------------------------------------------------------------------------

export type DriftTier = 0 | 1 | 2 | 3

export interface DriftState {
  readonly active: boolean
  /** -1 drifting left, +1 drifting right, 0 not drifting. */
  readonly direction: -1 | 0 | 1
  /** Seconds banked toward the next tier. */
  readonly charge: Seconds
  readonly tier: DriftTier
  /** Angle between chassis forward and velocity. Drives spark rate. */
  readonly slipAngle: Radians
}

export type BoostSource = 'none' | 'drift' | 'pad' | 'item' | 'slipstream'

export interface BoostState {
  readonly active: boolean
  readonly remaining: Seconds
  /** Multiplier on top speed. 1.0 means no boost. */
  readonly strength: number
  readonly source: BoostSource
}

/** `wall` is deliberately absent — wall contact emits `kart:wall` telemetry and
 *  applies no `HitKind`. One collision must not fire two effect paths. */
export type HitKind = 'spin' | 'squash' | 'bump'

/** Per-wheel visual telemetry. `kart/` simulates it; `render/` and `fx/` read it. */
export interface WheelState {
  /** Suspension compression, 0 = fully extended, 1 = bottomed out. */
  readonly compression: number
  /** Steer angle applied to this wheel. Sign follows STEERING SIGN. */
  readonly steerAngle: Radians
  /** Accumulated spin, radians. Wraps freely. */
  readonly spin: Radians
  readonly grounded: boolean
  readonly surface: Surface
  /** 0..1, how much this wheel is sliding. Drives spray and spark volume. */
  readonly slip: number
}

export interface KartState {
  readonly position: Vector3
  readonly quaternion: Quaternion
  readonly velocity: Vector3
  /** Signed m/s along chassis forward. Negative when reversing. */
  readonly speed: number
  /** Surface under the chassis centre. Per-wheel surfaces live in `wheels`. */
  readonly surface: Surface
  readonly grounded: boolean
  readonly drift: DriftState
  readonly boost: BoostState
  /** Front-left, front-right, rear-left, rear-right. */
  readonly wheels: readonly [WheelState, WheelState, WheelState, WheelState]
  /**
   * Seconds of lost control. While above zero the kart forces `steer = 0`,
   * which appears in input-latency measurements as a response hole. The touch
   * harness drops those frames rather than averaging them in.
   */
  readonly stunTime: Seconds
}

/** Presentation identity. Assigned centrally so UI, FX and render agree. */
export interface KartIdentity {
  readonly id: number
  readonly isPlayer: boolean
  readonly displayName: string
  /** Livery primary. Must not collide with the §3b reserved gameplay band. */
  readonly primaryColor: number
  readonly secondaryColor: number
  /** Stable seed for this kart's procedural decal. */
  readonly liverySeed: number
}

export interface IKart {
  readonly identity: KartIdentity
  readonly state: Readonly<KartState>
  /**
   * Attachment roots, with owners. `render/` fills `modelRoot`, `fx/` fills
   * `fxRoot`, `audio/` positions from `audioRoot`. Each owner disposes only
   * what it added, and only its own root's children.
   */
  readonly modelRoot: Object3D
  readonly fxRoot: Object3D
  readonly audioRoot: Object3D
  /** Fixed-step. Called once per simulation tick by the composition root. */
  step(step: Seconds, input: Readonly<InputFrame>): void
  /**
   * Boost composition: a new boost REPLACES the active one when its `strength`
   * is greater or equal, and otherwise only extends `remaining` if the incoming
   * duration would outlast it. Strengths never multiply — stacking pad, drift
   * and item must not produce a speed the balance was never tested at. Emits
   * `boost:start` on any change of source or strength.
   */
  applyBoost(seconds: Seconds, strength: number, source: BoostSource): void
  /** `incomingDirectionWorld` is a unit vector in WORLD space pointing from the
   *  source of the hit toward this kart. */
  applyHit(kind: HitKind, incomingDirectionWorld: Vector3): void
  /** Place on the racing line at `t`, stationary, facing forward, drift and
   *  boost and stun cleared. Checkpoint progress is preserved. */
  respawn(t: number): void
  /**
   * Place at an explicit track coordinate, at a given lateral offset from the
   * centreline, facing along the tangent. Same clearing behaviour as `respawn`.
   *
   * This exists for ONE reason and it is worth stating, because a pose setter is
   * otherwise exactly the kind of surface that invites abuse: without it the
   * steering-sign gate cannot run. That gate has to place a kart at a known
   * offset from the racing line and assert which way it moves, and it is the
   * cheapest available check on the most expensive class of bug this project
   * has — a sign error that makes the game drive correctly today and breaks
   * everything the next time either half changes.
   *
   * `game/` must not call this. Respawns go through `respawn`.
   */
  placeAt(t: number, lateral: Metres, speed?: number): void
}

// ---------------------------------------------------------------------------
// Race
// ---------------------------------------------------------------------------

export type RacePhase = 'idle' | 'countdown' | 'racing' | 'finished'

export interface Standing {
  readonly kartId: number
  /** 1-based finishing order or current place. */
  readonly place: number
  /** Laps fully completed. The grid shows 0; the HUD displays `completed + 1`. */
  readonly completedLaps: number
  /**
   * `completedLaps + t`. Race-order key. It can decrease when a kart drives
   * backward or is respawned behind its previous position — it is NOT
   * monotonic, and sorting must handle that. `bestProgress` is the monotonic
   * one, used only for stall detection.
   */
  readonly progress: number
  readonly bestProgress: number
  readonly lapTimes: readonly Seconds[]
  readonly finished: boolean
}

export interface IRace {
  readonly phase: RacePhase
  readonly totalLaps: number
  /** Seconds since GO. Negative through the countdown. */
  readonly clock: Seconds
  readonly standings: readonly Standing[]
  step(step: Seconds): void
  start(): void
  /** Return every kart to the grid and clear all progress. Synchronous. */
  reset(): void
}

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export type ItemKind = 'none' | 'boost' | 'projectile' | 'mine' | 'shield'

export interface IItems {
  step(step: Seconds): void
  held(kartId: number): ItemKind
  /**
   * Rolled from the authoritative standings at `tick`, read by `IItems` itself
   * through `GameServices.race` — the caller does not pass a place, because two
   * subsystems sampling standings at different moments roll different items and
   * the difference is invisible.
   */
  grant(kartId: number, tick: number): void
  use(kartId: number): void
  reset(): void
}

// ---------------------------------------------------------------------------
// Camera
// ---------------------------------------------------------------------------
/**
 * Exactly one subsystem writes the camera transform: `game/`, through
 * `follow`. Everything else contributes an ADDITIVE, decaying channel. Without
 * this split, `render/`, `fx/` and `kart/` all set `camera.position` and the
 * result is last-writer-wins, which reads as a camera bug with no owner.
 */
export interface ICameraRig {
  readonly camera: PerspectiveCamera
  /** Base follow. `game/` only. */
  follow(kart: IKart, step: Seconds): void
  /** Additive FOV impulse in degrees. `fx/` only. */
  addFovPunch(degrees: number, attackMs: number, decayMs: number): void
  /** Additive positional shake. `fx/` only. */
  addShake(intensity: number, durationMs: number): void
  /** Degrees per second of angular swing this tick. The nausea metric. */
  readonly swingDegPerSec: number
}

// ---------------------------------------------------------------------------
// Events — the only cross-subsystem channel besides GameServices
// ---------------------------------------------------------------------------
/**
 * Dispatch is SYNCHRONOUS, in registration order, over a snapshot of the
 * listener list taken at emit time — so subscribing or unsubscribing during
 * dispatch never changes who is called for the event in flight. A listener that
 * throws is logged and the remaining listeners still run; one broken effect
 * must not stop the audio. Re-entrant `emit` is legal and runs to completion
 * before the outer dispatch resumes.
 *
 * Payload objects are freshly allocated per emit. This is the one sanctioned
 * exception to the allocation rule, and it is why events are for discrete
 * moments only. Continuous per-tick data belongs in `GameServices`.
 *
 * Adding an event is a contract change. Say so in the commit.
 */
export interface GameEvents {
  'race:countdown': { readonly n: 3 | 2 | 1 | 0 }
  'race:start': Record<string, never>
  'race:finish': { readonly kartId: number; readonly place: number }
  'lap:complete': { readonly kartId: number; readonly lap: number; readonly lapTime: Seconds }

  'drift:start': { readonly kartId: number; readonly direction: -1 | 1 }
  'drift:tier': { readonly kartId: number; readonly tier: 1 | 2 | 3 }
  /** `tier: 0` means the drift was released before it banked anything. */
  'drift:release': {
    readonly kartId: number
    readonly tier: DriftTier
    readonly boostSeconds: Seconds
  }

  'boost:start': { readonly kartId: number; readonly seconds: Seconds; readonly source: BoostSource }
  'boost:end': { readonly kartId: number }

  'kart:land': { readonly kartId: number; readonly impactSpeed: number; readonly surface: Surface }
  'kart:hit': { readonly kartId: number; readonly kind: HitKind }
  /** Telemetry only. Fires no `kart:hit`; `fx/` may still spark off it. */
  'kart:wall': { readonly kartId: number; readonly speed: number }
  'kart:respawn': { readonly kartId: number }
  'surface:change': { readonly kartId: number; readonly from: Surface; readonly to: Surface }

  'item:pickup': { readonly kartId: number; readonly kind: ItemKind }
  'item:use': { readonly kartId: number; readonly kind: ItemKind }
  'item:hit': { readonly kartId: number; readonly by: number; readonly kind: ItemKind }
}

export type EventName = keyof GameEvents

export interface EventBus {
  on<K extends EventName>(name: K, fn: (payload: GameEvents[K]) => void): () => void
  emit<K extends EventName>(name: K, payload: GameEvents[K]): void
  /** Drop every listener. Harness runs build and tear down repeatedly. */
  clear(): void
}

// ---------------------------------------------------------------------------
// Quality & settings
// ---------------------------------------------------------------------------

export type QualityTier = 'low' | 'medium' | 'high' | 'ultra'

/**
 * Already clamped to the device. `render/` publishes the resolved profile after
 * querying real GPU limits; a profile asking for 2048² textures on a device
 * that caps at 1024 would otherwise fail at material-build time inside whichever
 * agent's code happened to run first.
 */
export interface QualityProfile {
  readonly tier: QualityTier
  /** Multiplier on device pixel ratio, before the adaptive scaler. */
  readonly renderScale: number
  readonly shadows: boolean
  readonly shadowCascades: 0 | 2 | 3 | 4
  readonly ssr: boolean
  readonly ssao: boolean
  readonly bloom: boolean
  readonly motionBlur: boolean
  /** Hard ceiling on live particles across every emitter. */
  readonly particleBudget: number
  /** Metres. Scenery beyond this drops to its lowest LOD. */
  readonly lodDistance: Metres
  /** Resolved: `min(requested, gl.MAX_TEXTURE_SIZE)`. */
  readonly maxTextureSize: number
  /** Resolved: `min(8, gl.getExtension(...).MAX_TEXTURE_MAX_ANISOTROPY_EXT)`. */
  readonly maxAnisotropy: number
}

export interface Settings {
  quality: QualityTier
  /** All volumes normalised [0, 1], clamped on write. */
  masterVolume: number
  musicVolume: number
  sfxVolume: number
  /** Scales camera swing and screen shake toward zero. */
  reducedMotion: boolean
  invertLook: boolean
}

// ---------------------------------------------------------------------------
// DETERMINISM
// ---------------------------------------------------------------------------
/**
 * Given the same seed, the same build must produce the same city, the same AI
 * lines and the same lap times. Critics compare screenshots across rounds and
 * harnesses compare frame times between builds; if the world rearranges itself
 * between loads, every one of those comparisons measures noise.
 *
 * Rules, all of them enforceable by review:
 *   - Randomness comes from `ctx.rngFor(namespace)`, never `Math.random()`.
 *     Each namespace is an independent stream seeded from `Ctx.seed` and the
 *     namespace string, so build order cannot shift which numbers a subsystem
 *     receives. One shared stream plus one added `await` silently rebuilds a
 *     different city with an identical seed.
 *   - No `Date.now()`, `performance.now()` or `crypto` in `build`, `fixedUpdate`
 *     or anything they call. Time comes from `Clock`.
 *   - Do not iterate a `Set` or object keyed by insertion order to produce
 *     geometry. Sort explicitly.
 *   - IDs are assigned by the composition root, never generated locally.
 *
 * Screenshots are compared with a documented perceptual tolerance, NOT byte
 * equality: driver and browser versions change shader output, and demanding
 * byte equality would make every review fail for the wrong reason.
 */
export interface RNG {
  (): number
  readonly namespace: string
  /** Independent child stream. Deterministic in `sub`, not in call order. */
  fork(sub: string): RNG
}

export interface Ctx {
  readonly scene: Scene
  readonly renderer: WebGLRenderer
  readonly events: EventBus
  readonly settings: Settings
  readonly quality: QualityProfile
  readonly clock: Clock
  readonly seed: number
  /** Independent per-namespace stream. Call once in `build`, retain the result. */
  rngFor(namespace: string): RNG
}

// ---------------------------------------------------------------------------
// Composition
// ---------------------------------------------------------------------------
/**
 * `src/main.ts` is the ONLY authorised composition root. It constructs each
 * subsystem through the factory signatures below, assembles `GameServices`, and
 * calls `link` on everything once every `build` has resolved.
 *
 * Lifecycle, in order, exactly once:
 *   1. `build(ctx)`   - may await, may allocate freely, may not read services
 *   2. `link(svc)`    - resolve cross-subsystem references; no heavy work
 *   3. per tick:  `fixedUpdate(SIMULATION_STEP, ctx)` in registration order
 *   4. per frame: `lateUpdate(dt, ctx)` in registration order, after catch-up
 *   5. `render/` presents. It is the only subsystem that touches the composer.
 *
 * `fixedUpdate` order is fixed by the root and is part of the contract:
 *   input -> kart physics -> race -> items -> camera
 * `lateUpdate` order:
 *   fx -> ui -> audio -> render
 * A subsystem that needs a different order is describing a data dependency it
 * should be reading from `GameServices` instead.
 */
export interface GameServices {
  readonly track: ITrack
  readonly input: IInput
  readonly race: IRace
  readonly items: IItems
  readonly camera: ICameraRig
  /** Stable identity order, index-aligned with `identities`. Never re-sorted. */
  readonly karts: readonly IKart[]
  readonly identities: readonly KartIdentity[]
  readonly playerKartId: number
  kartById(id: number): IKart | null
}

export interface Subsystem {
  readonly name: string
  build(ctx: Ctx): Promise<void> | void
  link?(services: GameServices, ctx: Ctx): void
  /** Deterministic, fixed-step. No wall clock, no allocation. */
  fixedUpdate?(step: Seconds, ctx: Ctx): void
  /** Once per rendered frame. Visual and audio only; never mutates simulation. */
  lateUpdate?(dt: Seconds, ctx: Ctx): void
  /** Free GPU resources. Harness runs create and destroy the world repeatedly. */
  dispose(): void
}

export type TrackFactory = (ctx: Ctx) => Promise<ITrack & Subsystem> | (ITrack & Subsystem)
export type KartFactory = (ctx: Ctx, identity: KartIdentity, slot: StartSlot) => IKart & Subsystem
export type InputFactory = (ctx: Ctx) => IInput & Subsystem
export type RaceFactory = (ctx: Ctx) => IRace & Subsystem
export type ItemsFactory = (ctx: Ctx) => IItems & Subsystem
export type CameraFactory = (ctx: Ctx) => ICameraRig & Subsystem
/** `render/`, `fx/`, `ui/`, `audio/` expose a plain Subsystem factory. */
export type PlainFactory = (ctx: Ctx) => Promise<Subsystem> | Subsystem

// ---------------------------------------------------------------------------
// ALLOCATION
// ---------------------------------------------------------------------------
/**
 * "Zero allocation" applies to NAMED HOT PATHS, not to everything, because a
 * blanket rule the API cannot satisfy is a rule nobody follows:
 *
 *   MUST NOT ALLOCATE
 *     - `Subsystem.fixedUpdate` and everything it calls
 *     - `IKart.step`, `ITrack.sample`, `ITrack.locate`, `ITrack.surfaceAt`
 *     - particle and trail update loops in `fx/`
 *
 *   MAY ALLOCATE
 *     - `build`, `link`, `dispose`
 *     - event payloads at `emit` (discrete moments only)
 *     - `lateUpdate` sparingly — HUD string formatting is allowed once per
 *       changed value, not once per frame
 *     - every `HarnessAPI` method; harness calls are not in the frame budget
 *
 * Where a hot path needs a vector, use a module-scope scratch object. Never
 * `new Vector3()` inside these functions.
 */

// ---------------------------------------------------------------------------
// Harness API — the measurement surface, not a debug convenience
// ---------------------------------------------------------------------------
/**
 * `tools/*.mjs` drive the game exclusively through this, and it ships in
 * production builds on purpose: a harness that measures a different build from
 * the one players run is not measuring anything.
 *
 * Every method returning a snapshot returns a DEEP VALUE COPY of plain numbers.
 * Handing out live references means the harness reads a value that changed
 * between the call and the assertion, and the resulting flakiness looks like a
 * game bug.
 */

export type VantageName =
  | 'grid'
  | 'dune-sweep'
  | 'strata-wall'
  | 'slot-narrows'
  | 'mesa-crest'
  | 'banked-wall'
  | 'wash-descent'
  | 'arch-interior'
  | 'arch-exit'
  | 'drift-tier3'

/**
 * Deterministic set-ups the harness can drive the game into. `loadScenario`
 * resolves on the exact presented frame the scenario is defined to measure, so
 * a peak-brightness or peak-tier moment is not something the harness has to
 * catch by polling and hope it did not miss.
 */
export type ScenarioName =
  | 'grid-idle'
  | 'tier3-boost-at-arch-exit'
  | 'tier3-release-open-road'
  | 'sand-drift-crossing'
  | 'cattle-grid-crossing'
  | 'full-field-first-corner'

export type DriverMode = 'human' | 'scripted' | 'referenceAI' | 'idle'

export interface FrameStats {
  /** Ticks and frames covered by this sample window. */
  readonly frames: number
  readonly fps: number
  /**
   * Gate on this, never on the median. At 60 Hz vsync only ever returns ~16.7
   * or ~33.4 ms, so a build running at 48 fps has a median of exactly 16.70 and
   * reads as a perfect pass.
   */
  readonly meanFrameMs: number
  readonly p95FrameMs: number
  /** Frames that consumed two or more vsync intervals. The real hitch signal. */
  readonly longFrames: number
  readonly drawCalls: number
  readonly triangles: number
  readonly programs: number
  readonly jsHeapMb: number | null
  readonly textureMemoryMb: number | null
}

export interface GLReport {
  /** `UNMASKED_RENDERER_WEBGL` from the context the game actually rendered with. */
  readonly renderer: string
  readonly vendor: string
  /**
   * True when the renderer string matches a known software rasteriser. A timing
   * number from SwiftShader is fiction, and headless Chrome falls back to it
   * silently while still returning confident numbers.
   */
  readonly isSoftware: boolean
  readonly maxTextureSize: number
  readonly maxAnisotropy: number
  readonly failedShaders: readonly string[]
  readonly contextLost: boolean
  readonly preserveDrawingBuffer: boolean
}

export interface TileLuma {
  readonly x: number
  readonly y: number
  readonly mean: number
  readonly stdDev: number
  readonly blackFraction: number
  readonly clippedFraction: number
}

/**
 * Whole-frame statistics plus an 8×8 tile grid.
 *
 * The tiles are the point. A half-black, half-correct frame has an excellent
 * whole-image standard deviation and passes any global check — partial-black
 * present is exactly the failure that looks healthy in aggregate.
 *
 * Reading the presented frame at all requires the context to have been created
 * with `preserveDrawingBuffer`; without it `readPixels` after present returns
 * discarded contents, which reads as "100% of frames are black" and is
 * completely false. `?debug=frames` sets it, and this call throws when it is
 * absent rather than returning a confident lie.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WHY THE UNPAINTED TEST KEYS ON UNIFORMITY AND NOT ON BRIGHTNESS
 *
 * It used to test darkness: a tile more than 98% below the black threshold
 * failed as a partial present. Measuring a real, correct, shipped neon-night
 * scene killed that rule outright — it had tiles at 98% and 99% black, because
 * a dark alley wall at 2 a.m. IS black to within a 24-bit encode. The detector
 * would have failed exactly the frame the art direction was aiming for.
 *
 * That measurement is kept here as calibration provenance even though the
 * project no longer ships a night scene, because it is what sets the 1e-5
 * threshold: the reference's darkest tiles measured standard deviations of
 * 8.2e-4 to 1.8e-2, against exactly 0 for a cleared buffer, so 1e-5 sits about
 * 80x below the smallest real value ever observed.
 *
 * The rule survived the switch to daylight; one of its clauses did not, and it
 * failed DANGEROUSLY. The old test was `stdDev < 1e-5 && mean < 0.004`. When
 * the clear colour is black those two conditions coincide and the second one
 * costs nothing. Under a bright sky they diverge: `setClearColor(skyColour)` is
 * an ordinary, defensible thing to write, and it would have silently disabled
 * the detector entirely. A sky shader that fails to compile and falls back to a
 * constant is the same hole. The brightness clause is gone.
 *
 * Daylight also brought an inverted failure that zero-variance cannot catch — a
 * nearly-but-not-exactly flat blown sky, or a procedural sand albedo returning
 * a constant. Hence `flatBrightTiles`.
 *
 * Both detectors rest on ART_DIRECTION §9b forbidding any perfectly uniform
 * region, sky included, and on §2 mandating sky dither. Those are art rules
 * doing double duty: remove either and the instrument starts lying.
 * ──────────────────────────────────────────────────────────────────────────
 */
export interface FrameLumaStats {
  readonly mean: number
  readonly stdDev: number
  /**
   * Fraction of pixels below the encode floor (luma < 0.004). Near zero on a
   * sunlit scene — the deepest legitimate surface, a niche under an overhang
   * seeing 8% of the sky and no sun, computes to luma 0.070. Reported for the
   * record, not gated on.
   */
  readonly blackFraction: number
  /**
   * Fraction of pixels below luma 0.05. Under a sun this is a MAXIMUM, not a
   * minimum — the gate that inverted with the theme. Anything under 0.05 is a
   * shadow term clamping to zero, missing skylight fill, or unlit geometry.
   */
  readonly darkFraction: number
  /**
   * Fraction of pixels at or above luma 0.5. On a night scene this measured
   * emissive AREA and was capped at 8%. Under a sun the same threshold measures
   * something else entirely: luma 0.5 is only 1.19x sunlit sand, so sand, rock
   * and sky all sit above it and a correct frame reads 60-80%. It survives as a
   * wide sanity rail — "is this actually a sunlit scene" — not as a budget.
   */
  readonly brightFraction: number
  /**
   * Fraction of pixels at or above luma 0.95. THIS is where "walks toward a
   * white screen" lives in daylight. Derived: 0.95 requires 6.6x sunlit sand,
   * about +2.7 stops, which only the near-sun haze band, the disc, specular
   * glints and bloom can reach.
   */
  readonly highlightFraction: number
  /** Fraction of pixels with luma >= 0.99. The §9a clipping gate. */
  readonly clippedFraction: number
  readonly tiles: readonly TileLuma[]
  /**
   * Tiles with `stdDev < 1e-5`, AT ANY BRIGHTNESS. Anything above zero means
   * part of the frame was never drawn. THIS is the partial-present assertion;
   * `worstTileBlackFraction` is not, and neither is darkness.
   */
  readonly unpaintedTiles: number
  /**
   * Tiles with `stdDev < 2e-3` and `mean >= 0.5` — painted, but with nothing in
   * them. A blown sky, a constant-colour fallback, an untextured sand plane.
   * Budget is at most one of 64: a single tile of open sky near the zenith can
   * legitimately be very smooth, and that allowance has not been measured.
   */
  readonly flatBrightTiles: number
  readonly worstTileBlackFraction: number
  readonly worstTileClippedFraction: number
}

/** Cumulative counters since the last `resetRace`. Reset atomically with it. */
export interface KartTelemetry {
  readonly kartId: number
  readonly driftAttempts: number
  /** Index is the tier reached at release: [tier0, tier1, tier2, tier3]. */
  readonly driftReleases: readonly [number, number, number, number]
  readonly boostSecondsBySource: Readonly<Record<BoostSource, Seconds>>
  readonly respawns: number
  readonly wallHits: number
  readonly lapTimes: readonly Seconds[]
  readonly bestLap: Seconds | null
  readonly finished: boolean
  readonly completedLaps: number
  readonly lastCheckpoint: number
  readonly t: number
  readonly lateral: Metres
  /** Ticks since `bestProgress` last increased. The stuck-on-a-wall detector. */
  readonly ticksWithoutProgress: number
}

export interface RaceTelemetry {
  readonly sinceTick: number
  readonly tick: number
  readonly phase: RacePhase
  readonly clock: Seconds
  readonly karts: readonly KartTelemetry[]
}

export interface InputLatencySample {
  readonly kind: InputKind
  /** `performance.now()` at injection. */
  readonly injectedAtMs: number
  /** `performance.now()` when `IInput.sample` first observed it. */
  readonly receivedAtMs: number
  /** Tick that consumed it. */
  readonly sampledTick: number
  /** Steer value the kart actually acted on. */
  readonly effectiveSteer: number
  /** True when `stunTime > 0` during the sample — contaminated, drop it. */
  readonly stunned: boolean
}

export interface ResetOptions {
  readonly seed?: number
  readonly quality?: QualityTier
  readonly totalLaps?: number
  /** Default `'referenceAI'` for every kart including the player. */
  readonly drivers?: Readonly<Record<number, DriverMode>>
  /**
   * Which way the reference AI drives.
   *
   * §10c criterion 1 — "a drifting lap is measurably faster than a clean lap" —
   * is a CONTROLLED COMPARISON, and without this there is no control.
   * `DriverMode` has no clean-line reference driver and `setInput` reaches only
   * the player kart, so the experiment simply could not be run. Defaults to
   * `'seek'`, which is how the game is meant to be played.
   */
  readonly aiDrift?: 'seek' | 'clean'
}

export interface HarnessAPI {
  readonly version: 2
  /** Resolves after the first frame has presented. */
  readonly ready: Promise<void>
  readonly playerKartId: number

  /**
   * The live circuit, BY REFERENCE — the one exception to the deep-copy rule
   * two paragraphs up, and it is a considered one.
   *
   * That rule exists because a live handle on CHANGING state goes stale between
   * the call and the assertion, and the resulting flakiness reads as a game bug.
   * A track is built once and immutable for the life of the world, so that
   * failure cannot occur here. A copy would also defeat the purpose: `locate`'s
   * per-call cost and its allocation-freedom are properties of the real
   * function, and they are exactly what needs measuring. The track is the one
   * subsystem whose serious bugs — a spline parameterised by anything other than
   * arc length, a lateral sign inverted, a frame that quietly stops being
   * orthonormal — are all completely invisible in a rendered frame.
   *
   * This hands out no privilege that `GameServices.track` does not already give
   * every subsystem.
   */
  readonly track: ITrack

  /**
   * The scene root and the live camera.
   *
   * `seam-check.mjs` reached the world through `track.group.parent`, which is a
   * load-bearing accident rather than a contract. And a camera is the
   * difference between proving the ground is watertight in GEOMETRY and proving
   * no hole is VISIBLE — which is exactly the class of miss that let the last
   * one ship. A harness with the camera can unproject the frame and gate on
   * pixels.
   */
  readonly scene: Object3D
  readonly camera: PerspectiveCamera

  /**
   * The input frame a driver produced on the last tick, human or AI.
   *
   * Without this, the STEERING SIGN rule is UNFALSIFIABLE. An AI that
   * compensates for an inverted chassis with a second negation drives around
   * the circuit perfectly; the outcome is correct and the command is wrong, and
   * nothing downstream can tell the difference. The next change to either sign
   * then breaks the game and both halves still look right in isolation.
   *
   * This exposes the command, so the convention can be tested where it is
   * actually stated rather than three layers downstream at `wheels[].steerAngle`.
   */
  lastInput(kartId: number): Readonly<InputFrame> | null

  /**
   * Full deterministic rebuild. Async because changing seed or quality replaces
   * GPU resources and regenerates the world; a synchronous `setSeed` would
   * leave `Ctx.seed` and every cached material disagreeing about which world
   * this is. Resolves once the new world has presented one frame.
   */
  resetRace(options?: ResetOptions): Promise<void>
  startRace(): void
  setDriver(kartId: number, mode: DriverMode): void

  /** Throws on an unknown name rather than silently invalidating a review run. */
  vantage(name: VantageName): Promise<void>
  loadScenario(name: ScenarioName): Promise<void>

  /**
   * PERSISTENT MERGE: omitted fields keep their previous injected value; the
   * frame persists until changed or released. Switches the player to
   * `'scripted'` if it is not already.
   */
  setInput(frame: Partial<InputFrame>): void
  releaseInput(): void
  /**
   * Push a frame through the real `IInput` implementation of the given kind,
   * stamped with an injection time, so latency measures the input path rather
   * than the physics response. Returns once the tick that consumed it has run.
   */
  injectInput(kind: InputKind, frame: Partial<InputFrame>, atMs: number): Promise<InputLatencySample>

  /** Teleport for a repeatable shot. Clears velocity, drift, boost and stun;
   *  preserves checkpoint progress unless `resetProgress` is true. */
  seek(options: {
    t: number
    /**
     * RELATIVE TO THE RACING LINE, not the centreline. The composition root
     * resolves it as `racingLine(t) + lateral`, so `lateral: 0` places the kart
     * ON the line — which on this circuit can be 13.46 m from centre.
     *
     * Stated here because its absence has now cost four separate measurement
     * runs. `steer-test.mjs` added `racingLine(t)` a second time and placed a
     * kart 22.6 m across a 14.0 m half-width road, then spent a round reporting
     * an inverted AI that did not exist. A wall probe placed a kart 5 m PAST
     * the barrier and reported a flawless 0.06 degree graze at tick 0. Both
     * read as plausible results.
     *
     * Contrast `IKart.placeAt`, whose offset is centreline-relative and says
     * so. The two are different and nothing but this comment says which is
     * which.
     */
    lateral?: Metres
    speed?: number
    resetProgress?: boolean
  }): Promise<void>

  /** Advance exactly `count` ticks ignoring wall clock, presenting each frame. */
  stepTicks(count: number): Promise<void>

  /** Open a measurement window. Statistics accumulate until `endSample`. */
  beginSample(): void
  endSample(): FrameStats

  frameLumaStats(): FrameLumaStats
  glReport(): GLReport
  telemetry(): RaceTelemetry
  kartSnapshot(kartId: number): Readonly<KartState> | null

  /**
   * The adaptive scaler spends a real 2 ms saving on extra pixels and reports
   * the same fps, which makes genuine optimisations invisible. Every A/B pins
   * it, and `scalerPinned` must report the truth — a harness that trusts a pin
   * that did not take is measuring nothing.
   */
  pinScaler(on: boolean): void
  scalerPinned(): boolean
}

declare global {
  interface Window {
    __harness?: HarnessAPI
  }
}
